### ISSUE TITLE
CElementProvider::CreateDUI failed | Failed to create DirectUI parser: E_FAIL

### ISSUE THREAD

**Issue by MuscularPuky** [Rectify11/RectifyControlPanel2#5]
can't enter in control panel settings. instead it displays following error:
![image](https://github.com/Rectify11/RectifyControlPanel2/assets/93962018/e60d176e-2d74-43ae-b2f4-393e8b7e1ea8)

I'm on 25997

**Comment by MishaProductions** [comment]
install at least 1 icon in rectify11 installer

**Comment by MuscularPuky** [comment]
> install at least 1 icon in rectify11 installer

I used well without installing any icon until v3.0. is this intentional?
