### ISSUE TITLE
Context Choices: error while creating process: 2 or 3

### ISSUE THREAD

**Issue by BlankFX1** [Rectify11/RectifyControlPanel2#8]
No matter what is choosen, it leads to this error. Either with a 2 or a 3.
```
startProc
error while creating process: 3
[OK]
```

![rectify1](https://github.com/Rectify11/RectifyControlPanel2/assets/26005942/a9e2e6a1-7f27-4119-bd75-f1f5b22c570a)

(Also, all Umlauts are screwed up in the german version. Who allowed Rectify to use german strings in the first place, when I didn't? I'd be fine with english strings. An option to configure is prefered.)

**Comment by MishaProductions** [comment]
Can you please show the contents of the c:\windows\nilesoft\ folder? The control panel uses the system locale, and I am not sure why Umlauts are wrong.

**Comment by MishaProductions** [comment]
should be fixed in latest build

**Comment by BlankFX1** [comment]
> Can you please show the contents of the c:\windows\nilesoft\ folder? The control panel uses the system locale, and I am not sure why Umlauts are wrong.

I can't as this folder doesn't even exist.
Did you by chance ask for the Nilesoft Shell-Folder? Because I was using the portable app back then (but do not plan to use Nilesoft at all anymore).

I also just did a complete re-install of Rectify11 with everything included except for Designs, Gadgets, Wallpapers and Avatars and now nothing works at all anymore except for RectifyStart.exe and the changed Application Icons.
Pressing "Check it out" in the RectifyStart.exe does nothing and the Easy theme switcher "Turn on"-Button changes to "Already turned on" without giving an tray icon.

**Comment by MishaProductions** [comment]
Which version did you install? Thought I fixed those issues.
